dist: xenial
language: python
python:
- '3.6'
jdk:
- oraclejdk7
addons:
  postgresql: '9.6'
install:
- pip uninstall --yes psqlgraph || true
- pip install pipenv
- pipenv install --dev --deploy --python `which python`
- pipenv graph
before_script:
- echo $JAVA_OPTS
- export JAVA_OPTS=-Xmx512m
- echo -e 'Host github.com\n\tStrictHostKeyChecking no\n' >> ~/.ssh/config
- pipenv run python test/setup_test_psqlgraph.py
script: pipenv run py.test -v test
before_deploy:
- sed -i.bak "s/=get_version()/='$TRAVIS_TAG'/g" setup.py
- cat setup.py
- if [ $(python setup.py --version) == '0.0.0' ]; then travis_terminate 1; fi
deploy:
  provider: pypi
  user: uc-ctds
  skip_existing: true
  skip_cleanup: true
  on:
    python: 3.6
    repo: uc-cdis/psqlgraph
    tags: true
    branch: develop
  password:
    secure: khIEk0A2HokgXEpNS3IbOvK4u/WAbohVz87S9HyZ51cQrrfV7MO+JPvmkhRvNicYxR00fJmOcMSNmwruh404cjdrBd0Dnw8fL6XElWkl1WwwkBb4MWDZUeZfQIx6fgAAbJZ0RBdt4vDhPDP3jbzGm8orLAqtZNXnFwd1RcFR8kidvOkTdKvZ32G/9OqgWOEB+f0gpJ9/HIrY9mGnXfX1BspA06d+HwaLTpbXd4Yo2aYHTQZnMSoKJuCFyxuMvK0vtuuzAXy5t59socYnJ4SuZutjU6zXIk8rduiUOCktkqlqXeKQ2rZCZL/v5nyoPF2aOt5CXu7GYlHhmAnIShd0JmPgmYJ0TKPGRuo/Wg+OJLw+KmTXzzUtIDWup/V+VJ9EFVMZF6ldSnWB9xyhvzWgjA4s6pEZbTAMBH+xoMy8aLgpFwW0gK3q5kLK/iYJLEHLgvS+H1kA7Rd9rNIpA+OCRj3CKJ/KgiSXyULJjQobyB5Jz+Ia71gn5bgH7F32doWjoCMZwBiTaSllpmR2LBWlaRT2h9lGQABGEDwoWy7HQic7+bkG3anTsdLe5rbQKI713ZRZaJiUjz8qkMSafTnbJC1wbk4rON7aqV7IWqj+znKslsD9Bwe+YPhTAZW4MvKRjqzQOBa9izTFA/4d6ZV+2FB3zL/G9SIxSeOnX2aJBc4=
env:
  global:
  - PIPENV_IGNORE_VIRTUALENVS=1
  - secure: fIv/fpUv8CYCjiAoaSDkYz3IF2Rbd5h5BRY+fKPRs6xDzcGCdqyTZq+zaToxnKMzYt51VHkVKcRyXunl/rPhoNEQAh5xTJ/fqvxUfTfdfd98IYZHCg/j9zK08SZcKmqqhbwPTgWjbkWYvU/Tj53YjZVELDj9LKUuJF5i4nJucr6RcdgebLKYlJjoeeLYaelYzjNP381K5IEKGL40clihK257L3dhP/l6xE/LJDyEfhD51c7H9S1S1+QO6tAqdBhuj8PeU72RXGAUgVQtHYLBNWHu9Ig7L99Ly6l+twbn6zec3nYGyi+KDzNZgflq1dgbGtXoIWVgY5R+ROwjtCwrW5I4u8A3cbKk7/91QJad9M2tCs4WKWNol/BqfsanZ6/4Shr+IKFEGpCq5temwvg6Wf+xgH22YLwJPgw5jzZV8YdfOnTwGXtC2LB/VBkmoSs00NVGR69IFXZ6V89jxX0AGVu+141oI54RJDnhpC2NDxP9LxZsRSEMepir28Wc055Jq8HRGAZtuk4WTDwEFMdbOidfQydpS28WIr+OUdhvdPf4UWMl/y5kJaB30tsfl9kB32gebjXyuhXO6ChLSI6O+cVukMbOewrCdf1ny+dVJbXf9jzqyR3a6DdlIfJ9sKV4RatP1rlPEQ5V61wYYpn8hAZvDvLnINPsgZEIbYRc2uA=
# gen3git release will try to pull old commits instead of just commits since last tag.
# Need to fix this (PXP-3383), then can uncomment after_deploy section
# For now just manually generate release notes.
#after_deploy:
#- pipenv run pip install gen3git
#- pipenv run gen3git release
